version: "3.5"

services:
  nginx:
    container_name: studi1_nginx
    image:  registry.gitlab.com/dev-up/docker/nginx:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.studi1.rule=Host(`studi.local.qks.io`)
    volumes:
      - ./:/var/www/html
      - ./log/nginx:/var/log/nginx
    networks:
      - php
      - proxy

  php:
    container_name: studi1_php
    image:  registry.gitlab.com/dev-up/docker/php:latest
    volumes:
      - ./:/var/www/html
      - ./log/php:/var/log/dev-up
    networks:
      - php
      - mysql
      - gotenberg

  php-worker:
    container_name: studi1_worker_php
    image:  registry.gitlab.com/dev-up/docker/php:worker
    environment:
      TRANSPORT_NAME: scheduler_default async_priority_high async_priority_normal async_priority_low
    volumes:
      - ./:/var/www/html
      - ./log/php:/var/log/dev-up
    networks:
      - php
      - mysql
    restart: unless-stopped

  mysql:
    container_name: studi1_mysql
    image: registry.gitlab.com/dev-up/docker/mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: studi1
      MARIADB_DATABASE: studi1
      MARIADB_PASSWORD: studi1
      MARIADB_USER: studi1
      MYSQL_ROOT_HOST: localhost
    volumes:
      - ../database/studi1/data:/var/lib/mysql
    networks:
      - mysql

  adminer:
    container_name: studi1_adminer
    image: adminer
    labels:
      - traefik.enable=true
      - traefik.http.routers.adminerstudi1.rule=Host(`adminer-studi.local.qks.io`)
    networks:
      - proxy
      - mysql
    environment:
      - ADMINER_DESIGN=haeckel

  gotenberg:
    container_name: studi1_gotenberg
    image:  gotenberg/gotenberg:7.4.3
    networks:
      - gotenberg

networks:
  php:
    external: false
  mysql:
    external: false
  proxy:
    external: true
  gotenberg:
    external: false
